import React from 'react';

// ===========================================
// SETUP STYLES — Extracted from setup/page.tsx
// ===========================================

// ── Progress Bar Styles ──
export const procStyles: { [key: string]: React.CSSProperties } = {
  bar: {
    position: 'sticky',
    top: 0,
    zIndex: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0',
    padding: '12px 24px',
    background: 'rgba(12, 18, 32, 0.95)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(30, 64, 175, 0.15)',
  },
  stepWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  connector: {
    width: '32px',
    height: '2px',
    borderRadius: '1px',
    marginRight: '8px',
  },
  dot: {
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    border: '2px solid transparent',
  },
  label: {
    fontSize: '11px',
    letterSpacing: '0.03em',
    whiteSpace: 'nowrap',
  },
};

// ===========================================
// CELEBRATION STYLES
// ===========================================
export const celebrationStyles: { [key: string]: React.CSSProperties } = {
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 9999,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(12, 18, 32, 0.92)',
    backdropFilter: 'blur(8px)',
    overflow: 'hidden',
  },
  card: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    padding: '48px 40px 36px',
    background: 'rgba(30, 41, 59, 0.8)',
    border: '1px solid rgba(59, 130, 246, 0.3)',
    borderRadius: '20px',
    maxWidth: '480px',
    width: '90%',
    animation: 'celebration-fadeIn 0.6s ease-out forwards',
  },
  iconRing: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    background: 'rgba(245, 158, 11, 0.12)',
    border: '2px solid rgba(245, 158, 11, 0.3)',
    marginBottom: '20px',
    animation: 'celebration-pulse 2s ease-in-out infinite',
  },
  title: {
    fontSize: '28px',
    fontWeight: 800,
    color: '#F8FAFC',
    margin: '0 0 10px',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '14px',
    color: '#94A3B8',
    lineHeight: 1.6,
    margin: '0 0 24px',
    maxWidth: '380px',
  },
  badgeRow: {
    display: 'flex',
    gap: '10px',
    marginBottom: '28px',
    flexWrap: 'wrap' as React.CSSProperties['flexWrap'],
    justifyContent: 'center',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 14px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#CBD5E1',
    background: 'rgba(30, 64, 175, 0.15)',
    border: '1px solid rgba(59, 130, 246, 0.2)',
    borderRadius: '20px',
  },
  downloadBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    padding: '14px 28px',
    fontSize: '15px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #1E40AF, #3B82F6)',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
    marginBottom: '16px',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
  },
  redirectNote: {
    fontSize: '12px',
    color: '#475569',
    margin: 0,
    fontStyle: 'italic',
  },

  // Compliance Management Section
  complianceSection: {
    width: '100%',
    marginTop: '20px',
    marginBottom: '20px',
    padding: '16px',
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(30, 64, 175, 0.2)',
    borderRadius: '14px',
  },
  complianceSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '14px',
  },
  complianceSectionTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#60A5FA',
    letterSpacing: '0.02em',
  },
  auditBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '12px 16px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#E2E8F0',
    background: 'rgba(30, 64, 175, 0.15)',
    border: '1px solid rgba(96, 165, 250, 0.25)',
    borderRadius: '10px',
    cursor: 'pointer',
    marginBottom: '8px',
    transition: 'background 0.15s ease',
  },
  certDownloadBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '12px 16px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#86EFAC',
    background: 'rgba(34, 197, 94, 0.08)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'background 0.15s ease',
  },

  // Audit Modal
  auditOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 10000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0, 0, 0, 0.8)',
    backdropFilter: 'blur(8px)',
    padding: '24px',
  },
  auditModalContent: {
    width: '100%',
    maxWidth: '580px',
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column',
    background: '#0F172A',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '20px',
    overflow: 'hidden',
  },
  auditModalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px 24px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
    flexShrink: 0,
  },
  auditModalHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  auditModalTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#F8FAFC',
    margin: 0,
  },
  auditModalCloseBtn: {
    background: 'none',
    border: 'none',
    color: '#94A3B8',
    fontSize: '24px',
    cursor: 'pointer',
    lineHeight: 1,
    padding: '4px 8px',
  },
  auditModalBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px',
  },
  auditProvisionBox: {
    padding: '16px',
    background: 'rgba(30, 64, 175, 0.1)',
    border: '1px solid rgba(59, 130, 246, 0.2)',
    borderRadius: '12px',
    marginBottom: '20px',
  },
  auditSpinnerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  auditSpinner: {
    width: '16px',
    height: '16px',
    border: '2px solid rgba(59, 130, 246, 0.3)',
    borderTopColor: '#3B82F6',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    flexShrink: 0,
  },
  auditProvisionLabel: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#60A5FA',
  },
  auditProvisionDesc: {
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
    margin: 0,
  },
  auditCapSection: {
    marginBottom: '20px',
  },
  auditCapTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    margin: '0 0 12px',
  },
  auditCapGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  auditCapItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    padding: '10px 12px',
    background: 'rgba(30, 41, 59, 0.5)',
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.05)',
  },
  auditCapName: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 600,
    color: '#E2E8F0',
    marginBottom: '2px',
  },
  auditCapDesc: {
    display: 'block',
    fontSize: '11px',
    color: '#64748B',
    lineHeight: 1.5,
  },
  auditTimeline: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    paddingLeft: '8px',
  },
  auditTimelineItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  auditTimelineDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  auditTimelineLabel: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 600,
    color: '#E2E8F0',
  },
  auditTimelineTime: {
    display: 'block',
    fontSize: '11px',
    color: '#64748B',
  },
  auditModalFooter: {
    padding: '16px 24px',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    flexShrink: 0,
  },
  auditDoneBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '14px 24px',
    fontSize: '14px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #1E40AF, #3B82F6)',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
  },
};

// ===========================================
// STYLES
// ===========================================
export const styles: { [key: string]: React.CSSProperties } = {
  page: {
    minHeight: '100vh',
    background: '#0C1220',
    paddingTop: '0',
  },
  // ── Tenant Isolation Header ──
  isolationBar: {
    position: 'sticky' as const,
    top: 0,
    zIndex: 100,
    background: 'rgba(15, 23, 42, 0.95)',
    borderBottom: '1px solid rgba(34, 197, 94, 0.25)',
    backdropFilter: 'blur(12px)',
    padding: '8px 24px',
  },
  isolationBarInner: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    fontFamily: 'monospace',
    fontSize: '12px',
  },
  isolationLabel: {
    color: '#64748B',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  isolationValue: {
    color: '#22c55e',
    fontWeight: 700,
  },
  isolationSep: {
    color: '#334155',
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '40px 24px 80px',
  },
  header: {
    textAlign: 'center',
    marginBottom: '40px',
  },
  headerBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(30, 64, 175, 0.15)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#60A5FA',
    marginBottom: '20px',
  },
  headerTitle: {
    fontSize: '36px',
    fontWeight: 800,
    letterSpacing: '-0.03em',
    margin: '0 0 12px 0',
    color: '#F8FAFC',
  },
  headerSubtitle: {
    fontSize: '16px',
    color: '#94A3B8',
    margin: 0,
  },
  progressContainer: {
    marginBottom: '40px',
  },
  progressHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  progressLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#64748B',
    letterSpacing: '0.1em',
  },
  progressPercent: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#3B82F6',
  },
  progressTrack: {
    height: '6px',
    background: 'rgba(30, 64, 175, 0.2)',
    borderRadius: '10px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #1E40AF 0%, #3B82F6 100%)',
    borderRadius: '10px',
    transition: 'width 0.3s ease',
  },
  mainGrid: {
    display: 'grid',
    gridTemplateColumns: '260px 1fr',
    gap: '32px',
  },
  sidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  sidebarItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid',
    transition: 'all 0.2s ease',
  },
  sidebarIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  sidebarText: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  sidebarTitle: {
    fontSize: '14px',
    fontWeight: 600,
  },
  sidebarDesc: {
    fontSize: '12px',
    color: '#64748B',
  },
  contentArea: {
    minHeight: '500px',
  },
  card: {
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(30, 64, 175, 0.2)',
    borderRadius: '16px',
    padding: '32px',
  },
  cardTitle: {
    fontSize: '22px',
    fontWeight: 700,
    color: '#F8FAFC',
    margin: '0 0 8px 0',
  },
  cardDesc: {
    fontSize: '14px',
    color: '#94A3B8',
    margin: '0 0 28px 0',
  },
  formGroup: {
    marginBottom: '24px',
  },
  label: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '13px',
    fontWeight: 600,
    color: '#CBD5E1',
    marginBottom: '8px',
  },
  required: {
    color: '#EF4444',
    marginLeft: '4px',
  },
  fieldHint: {
    fontSize: '12px',
    color: '#64748B',
    margin: '0 0 12px 0',
  },
  helperText: {
    fontSize: '12px',
    color: '#64748B',
    margin: '8px 0 0 0',
    fontStyle: 'italic',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '14px',
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.8)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '10px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '14px',
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.8)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '10px',
    outline: 'none',
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '14px',
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.8)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '10px',
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  toneGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '16px',
  },
  toneCard: {
    padding: '24px',
    border: '2px solid',
    borderRadius: '16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  toneHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '16px',
  },
  toneIcon: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toneCheck: {
    width: '24px',
    height: '24px',
    borderRadius: '8px',
    border: '2px solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toneTitle: {
    fontSize: '18px',
    fontWeight: 700,
    margin: '0 0 8px 0',
  },
  toneDescription: {
    fontSize: '13px',
    color: '#94A3B8',
    margin: '0 0 16px 0',
    lineHeight: 1.5,
  },
  toneExamples: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  toneExamplesLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase',
  },
  toneExample: {
    fontSize: '12px',
    color: '#94A3B8',
    fontStyle: 'italic',
    paddingLeft: '12px',
    borderLeft: '2px solid rgba(30, 64, 175, 0.3)',
  },
  criticalField: {
    position: 'relative',
    padding: '24px',
    background: 'rgba(239, 68, 68, 0.05)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  criticalBadge: {
    position: 'absolute',
    top: '-10px',
    left: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 12px',
    background: '#EF4444',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
    color: '#fff',
    letterSpacing: '0.05em',
  },
  hoursMatrix: {
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(30, 64, 175, 0.2)',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  hoursHeader: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 16px',
    background: 'rgba(30, 64, 175, 0.1)',
    borderBottom: '1px solid rgba(30, 64, 175, 0.2)',
    fontSize: '11px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  hoursHeaderDay: {
    width: '60px',
  },
  hoursHeaderTime: {
    flex: 1,
    textAlign: 'center',
  },
  hoursHeaderToggle: {
    width: '60px',
    textAlign: 'center',
  },
  hoursRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 16px',
    borderBottom: '1px solid rgba(30, 64, 175, 0.1)',
    transition: 'opacity 0.2s ease',
  },
  hoursDay: {
    width: '60px',
    fontSize: '14px',
    fontWeight: 600,
    color: '#F8FAFC',
  },
  hoursInput: {
    flex: 1,
    maxWidth: '120px',
    margin: '0 12px',
    padding: '8px 12px',
    fontSize: '13px',
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '6px',
    outline: 'none',
  },
  hoursToggle: {
    width: '40px',
    height: '22px',
    borderRadius: '11px',
    border: 'none',
    cursor: 'pointer',
    padding: '0',
    marginLeft: 'auto',
  },
  hoursToggleThumb: {
    width: '18px',
    height: '18px',
    background: '#fff',
    borderRadius: '9px',
    transition: 'margin-left 0.2s ease',
  },
  hoursCounter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '12px',
    padding: '10px 14px',
    border: '1px solid rgba(34, 197, 94, 0.3)',
    borderRadius: '8px',
    background: 'rgba(34, 197, 94, 0.06)',
  },
  hoursCounterLabel: {
    fontSize: '13px',
    fontWeight: 500,
    color: '#94A3B8',
  },
  hoursCounterValue: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#22C55E',
    fontFamily: 'monospace',
  },
  hoursWarning: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '8px',
    padding: '10px 14px',
    background: 'rgba(239, 68, 68, 0.08)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: 500,
    color: '#EF4444',
  },
  radioGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  radioOption: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    padding: '16px',
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(30, 64, 175, 0.2)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  radioInput: {
    marginTop: '4px',
    accentColor: '#3B82F6',
  },
  radioContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  radioLabel: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#F8FAFC',
  },
  radioDesc: {
    fontSize: '12px',
    color: '#64748B',
  },
  deptTableHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    background: 'rgba(30, 64, 175, 0.1)',
    borderRadius: '10px 10px 0 0',
    fontSize: '11px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  deptList: {
    display: 'flex',
    flexDirection: 'column',
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(30, 64, 175, 0.2)',
    borderTop: 'none',
    borderRadius: '0 0 10px 10px',
  },
  deptRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    borderBottom: '1px solid rgba(30, 64, 175, 0.1)',
  },
  deptInput: {
    padding: '10px 14px',
    fontSize: '13px',
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '8px',
    outline: 'none',
  },
  deptRemoveBtn: {
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '8px',
    color: '#EF4444',
    cursor: 'pointer',
  },
  addDeptBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '16px',
    padding: '12px 20px',
    background: 'rgba(30, 64, 175, 0.15)',
    border: '1px dashed rgba(30, 64, 175, 0.4)',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: 600,
    color: '#60A5FA',
    cursor: 'pointer',
  },
  deptNote: {
    marginTop: '16px',
    padding: '12px 16px',
    background: 'rgba(59, 130, 246, 0.1)',
    borderRadius: '8px',
    fontSize: '12px',
    color: '#94A3B8',
  },
  // Knowledge Base Styles
  knowledgeSection: {
    marginBottom: '32px',
    padding: '24px',
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(30, 64, 175, 0.2)',
    borderRadius: '12px',
  },
  knowledgeSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '8px',
  },
  knowledgeSectionTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#F8FAFC',
    margin: 0,
  },
  knowledgeSectionDesc: {
    fontSize: '13px',
    color: '#94A3B8',
    margin: '0 0 20px 0',
  },
  dropZone: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 24px',
    border: '2px dashed',
    borderRadius: '12px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  dropZoneText: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#F8FAFC',
    margin: '0 0 8px 0',
  },
  dropZoneHint: {
    fontSize: '13px',
    color: '#64748B',
    margin: 0,
  },
  fileList: {
    marginTop: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  fileItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    background: 'rgba(59, 130, 246, 0.1)',
    border: '1px solid rgba(59, 130, 246, 0.2)',
    borderRadius: '8px',
  },
  fileInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  fileName: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#F8FAFC',
  },
  fileSize: {
    fontSize: '12px',
    color: '#64748B',
  },
  fileRemoveBtn: {
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '6px',
    color: '#EF4444',
    cursor: 'pointer',
  },
  goldenRulesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  goldenRuleItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    padding: '16px',
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '10px',
  },
  goldenRuleNumber: {
    width: '28px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(59, 130, 246, 0.2)',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#60A5FA',
    flexShrink: 0,
  },
  goldenRuleInputs: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  goldenRuleInput: {
    width: '100%',
    padding: '10px 14px',
    fontSize: '13px',
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.8)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '8px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  goldenRuleRemoveBtn: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '8px',
    color: '#EF4444',
    cursor: 'pointer',
    flexShrink: 0,
  },
  addRuleBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '16px',
    padding: '12px 20px',
    background: 'rgba(30, 64, 175, 0.15)',
    border: '1px dashed rgba(30, 64, 175, 0.4)',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: 600,
    color: '#60A5FA',
    cursor: 'pointer',
  },
  goldenRulesEmpty: {
    padding: '20px',
    textAlign: 'center',
    color: '#64748B',
    fontSize: '13px',
  },
  knowledgeValidation: {
    display: 'flex',
    gap: '24px',
    padding: '16px 20px',
    background: 'rgba(15, 23, 42, 0.4)',
    borderRadius: '10px',
    marginBottom: '16px',
  },
  validationItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
  },
  validationDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
  },
  knowledgeWarning: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    background: 'rgba(245, 158, 11, 0.1)',
    border: '1px solid rgba(245, 158, 11, 0.3)',
    borderRadius: '8px',
    fontSize: '13px',
    color: '#F59E0B',
    marginBottom: '16px',
  },
  crisisWarning: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '16px',
    padding: '20px',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  emergencyField: {
    padding: '24px',
    background: 'rgba(239, 68, 68, 0.05)',
    border: '2px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  emergencyLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '16px',
    fontWeight: 700,
    color: '#EF4444',
    marginBottom: '8px',
  },
  emergencyInput: {
    width: '100%',
    padding: '16px 20px',
    fontSize: '20px',
    fontWeight: 600,
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.8)',
    border: '2px solid rgba(239, 68, 68, 0.4)',
    borderRadius: '10px',
    outline: 'none',
    fontFamily: 'monospace',
    letterSpacing: '2px',
    boxSizing: 'border-box',
  },
  keywordsSection: {
    marginBottom: '16px',
  },
  keywordsSectionLabel: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 600,
    color: '#64748B',
    marginBottom: '8px',
  },
  keywordsList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '12px',
  },
  defaultKeyword: {
    padding: '6px 12px',
    background: 'rgba(239, 68, 68, 0.15)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 500,
    color: '#EF4444',
  },
  customKeyword: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    background: 'rgba(59, 130, 246, 0.15)',
    border: '1px solid rgba(59, 130, 246, 0.3)',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 500,
    color: '#60A5FA',
  },
  noKeywords: {
    fontSize: '12px',
    color: '#64748B',
    fontStyle: 'italic',
  },
  keywordRemoveBtn: {
    background: 'transparent',
    border: 'none',
    color: '#60A5FA',
    fontSize: '16px',
    cursor: 'pointer',
    padding: 0,
    lineHeight: 1,
  },
  addKeywordRow: {
    display: 'flex',
    gap: '12px',
  },
  keywordInput: {
    flex: 1,
    padding: '10px 14px',
    fontSize: '13px',
    color: '#F8FAFC',
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '8px',
    outline: 'none',
  },
  addKeywordBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 16px',
    background: '#1E40AF',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#fff',
    cursor: 'pointer',
  },
  complianceBox: {
    padding: '20px',
    background: 'rgba(34, 197, 94, 0.05)',
    border: '1px solid rgba(34, 197, 94, 0.2)',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  complianceTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    fontWeight: 600,
    color: '#22C55E',
    margin: '0 0 16px 0',
  },
  complianceList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    fontSize: '13px',
    color: '#CBD5E1',
  },
  cardFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    marginTop: '32px',
    paddingTop: '24px',
    borderTop: '1px solid rgba(30, 64, 175, 0.15)',
  },
  primaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    background: '#1E40AF',
    color: '#fff',
    padding: '14px 28px',
    borderRadius: '10px',
    fontSize: '15px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  secondaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '14px 24px',
    fontSize: '15px',
    fontWeight: 500,
    color: '#94A3B8',
    background: 'transparent',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    borderRadius: '10px',
    cursor: 'pointer',
  },
  launchBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    background: 'linear-gradient(135deg, #1E40AF 0%, #3B82F6 100%)',
    color: '#fff',
    padding: '14px 32px',
    borderRadius: '10px',
    fontSize: '15px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  spinner: {
    width: '18px',
    height: '18px',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    borderTopColor: '#fff',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  // Civic Integrations Styles
  integrationZone: {
    padding: '24px',
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(30, 64, 175, 0.2)',
    borderRadius: '12px',
    marginBottom: '20px',
  },
  integrationZoneHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '8px',
  },
  integrationZoneTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#F8FAFC',
    margin: 0,
  },
  integrationZoneDesc: {
    fontSize: '13px',
    color: '#94A3B8',
    margin: '0 0 20px 0',
    lineHeight: 1.5,
  },
  integrationWarning: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    margin: '8px 0 0 0',
    fontSize: '12px',
    color: '#F59E0B',
  },
  integrationSummary: {
    display: 'flex',
    gap: '24px',
    padding: '16px 20px',
    background: 'rgba(15, 23, 42, 0.4)',
    borderRadius: '10px',
    marginBottom: '8px',
  },
  integrationSummaryItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  integrationDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  // Review Step Styles
  incompleteBadge: {
    marginLeft: 'auto',
    padding: '3px 10px',
    background: 'rgba(239, 68, 68, 0.15)',
    border: '1px solid rgba(239, 68, 68, 0.4)',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
    color: '#EF4444',
    letterSpacing: '0.03em',
  },
  validationWarning: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '14px 18px',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '10px',
    fontSize: '13px',
    color: '#EF4444',
    marginTop: '8px',
  },
  reviewSection: {
    padding: '20px',
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(30, 64, 175, 0.15)',
    borderRadius: '12px',
    marginBottom: '16px',
  },
  reviewSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
  },
  reviewSectionTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#F8FAFC',
    margin: 0,
  },
  reviewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
  },
  reviewItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  reviewLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  reviewValue: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#F8FAFC',
  },
  reviewList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  reviewListItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 12px',
    background: 'rgba(30, 64, 175, 0.08)',
    borderRadius: '8px',
  },

  // AI Transparency Section
  transparencySection: {
    padding: '24px',
    background: 'rgba(168, 85, 247, 0.06)',
    border: '1px solid rgba(168, 85, 247, 0.25)',
    borderRadius: '12px',
    marginTop: '16px',
  },
  transparencySectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '12px',
  },
  transparencySectionTitle: {
    margin: 0,
    fontSize: '15px',
    fontWeight: 700,
    color: '#E2E8F0',
  },
  transparencyBadge: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#A855F7',
    background: 'rgba(168, 85, 247, 0.15)',
    padding: '3px 10px',
    borderRadius: '99px',
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  transparencyDesc: {
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.5,
    margin: '0 0 20px 0',
  },
  modelCardBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#A855F7',
    background: 'rgba(168, 85, 247, 0.1)',
    border: '1px solid rgba(168, 85, 247, 0.3)',
    borderRadius: '8px',
    cursor: 'pointer',
    marginBottom: '20px',
  },
  transparencyCheckboxLabel: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    cursor: 'pointer',
    padding: '14px 16px',
    background: 'rgba(168, 85, 247, 0.08)',
    borderRadius: '8px',
    border: '1px solid rgba(168, 85, 247, 0.15)',
  },
  transparencyCheckbox: {
    marginTop: '2px',
    accentColor: '#A855F7',
    flexShrink: 0,
    width: '16px',
    height: '16px',
  },
  transparencyCheckboxText: {
    fontSize: '13px',
    color: '#CBD5E1',
    lineHeight: 1.5,
  },

  // Model Card Modal
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    padding: '24px',
  },
  modalContent: {
    width: '100%',
    maxWidth: '560px',
    background: '#1E293B',
    border: '1px solid rgba(168, 85, 247, 0.3)',
    borderRadius: '16px',
    overflow: 'hidden',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px 24px',
    borderBottom: '1px solid rgba(30, 64, 175, 0.2)',
  },
  modalHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '17px',
    fontWeight: 700,
    color: '#F8FAFC',
  },
  modalCloseBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    background: 'rgba(255, 255, 255, 0.05)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '8px',
    color: '#94A3B8',
    cursor: 'pointer',
  },
  modalBody: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0px',
  },
  modelCardRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '16px',
    padding: '14px 0',
    borderBottom: '1px solid rgba(30, 64, 175, 0.12)',
  },
  modelCardLabel: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#94A3B8',
    flexShrink: 0,
    minWidth: '140px',
  },
  modelCardValue: {
    fontSize: '13px',
    color: '#E2E8F0',
    lineHeight: 1.5,
    textAlign: 'right' as const,
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    padding: '16px 24px',
    borderTop: '1px solid rgba(30, 64, 175, 0.2)',
  },
  modalDoneBtn: {
    padding: '10px 24px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#F8FAFC',
    background: '#A855F7',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
  },

  // Coverage Warning
  coverageWarning: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    padding: '16px',
    background: 'rgba(245, 158, 11, 0.06)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
    borderRadius: '10px',
    marginBottom: '8px',
  },

  // Clear Draft
  clearDraftRow: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '32px',
    paddingBottom: '24px',
  },
  clearDraftBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 24px',
    fontSize: '13px',
    fontWeight: 500,
    color: '#EF4444',
    background: 'transparent',
    border: '1px dashed rgba(239, 68, 68, 0.3)',
    borderRadius: '10px',
    cursor: 'pointer',
  },

  // Infrastructure Status Bar — Sovereignty Handshake
  infraBar: {
    width: '100%',
    background: 'rgba(15, 23, 42, 0.95)',
    borderBottom: '1px solid rgba(30, 64, 175, 0.2)',
    backdropFilter: 'blur(8px)',
    padding: '10px 0',
  },
  infraBarInner: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '13px',
    fontWeight: 500,
  },
  infraBarText: {
    color: '#CBD5E1',
    letterSpacing: '0.01em',
  },
  infraBadge: {
    display: 'inline-flex',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: 'monospace',
    background: 'rgba(30, 64, 175, 0.2)',
    color: '#60A5FA',
    border: '1px solid rgba(30, 64, 175, 0.3)',
    letterSpacing: '0.02em',
    textTransform: 'uppercase' as const,
  },
  infraBadgeGreen: {
    display: 'inline-flex',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 700,
    background: 'rgba(34, 197, 94, 0.15)',
    color: '#22C55E',
    border: '1px solid rgba(34, 197, 94, 0.3)',
  },
  infraBadgeNeutral: {
    display: 'inline-flex',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: 'monospace',
    background: 'rgba(100, 116, 139, 0.15)',
    color: '#94A3B8',
    border: '1px solid rgba(100, 116, 139, 0.2)',
    textTransform: 'uppercase' as const,
  },

  // Neutrality Initialization — Sovereignty Handshake
  neutralityItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    marginTop: '8px',
    borderRadius: '10px',
    background: 'rgba(234, 179, 8, 0.05)',
    border: '1px solid rgba(234, 179, 8, 0.15)',
    transition: 'all 0.3s ease',
  },
  neutralityIcon: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'all 0.3s ease',
  },
  neutralityText: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2px',
  },
  neutralityLabel: {
    fontSize: '13px',
    fontWeight: 600,
    transition: 'color 0.3s ease',
  },
  neutralityDesc: {
    fontSize: '11px',
    color: '#64748B',
    fontWeight: 500,
  },

  // Auto-Legislated Procurement — Resolution Drafter
  resolutionSection: {
    padding: '24px',
    background: 'rgba(245, 158, 11, 0.04)',
    border: '1px solid rgba(245, 158, 11, 0.15)',
    borderRadius: '12px',
    marginTop: '24px',
  },
  resolutionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '12px',
  },
  resolutionSectionTitle: {
    fontSize: '15px',
    fontWeight: 700,
    color: '#FDE68A',
    margin: 0,
  },
  resolutionBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.12)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
    letterSpacing: '0.02em',
    textTransform: 'uppercase' as const,
  },
  resolutionDesc: {
    fontSize: '13px',
    lineHeight: 1.6,
    color: '#94A3B8',
    margin: '0 0 16px 0',
  },
  draftResolutionBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #B45309, #F59E0B)',
    border: '1px solid rgba(245, 158, 11, 0.4)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  // ── Transparency & Public Trust Portal ──
  transparencyPortalSection: {
    background: 'rgba(6, 182, 212, 0.04)',
    border: '1px solid rgba(6, 182, 212, 0.15)',
    borderRadius: '14px',
    padding: '24px',
  },
  transparencyPortalHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '18px',
  },
  transparencyPortalTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 700,
    color: '#E2E8F0',
    letterSpacing: '-0.01em',
  },
  transparencyPortalBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#06B6D4',
    background: 'rgba(6, 182, 212, 0.12)',
    border: '1px solid rgba(6, 182, 212, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  foiaCard: {
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(6, 182, 212, 0.12)',
    borderRadius: '10px',
    padding: '18px',
    marginBottom: '16px',
  },
  foiaCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  foiaCardTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#E2E8F0',
  },
  foiaCardText: {
    margin: '0 0 14px 0',
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  foiaLinkPreview: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 14px',
    background: 'rgba(6, 182, 212, 0.06)',
    border: '1px solid rgba(6, 182, 212, 0.1)',
    borderRadius: '8px',
    marginBottom: '14px',
  },
  foiaLinkUrl: {
    flex: 1,
    fontSize: '12px',
    fontFamily: 'monospace',
    color: '#06B6D4',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  foiaLinkStatus: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#F59E0B',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  foiaConfigureBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 18px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#06B6D4',
    background: 'rgba(6, 182, 212, 0.1)',
    border: '1px solid rgba(6, 182, 212, 0.25)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  foiaConfigureBtnDone: {
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
  },
  foiaComplianceNote: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    padding: '14px 16px',
    background: 'rgba(6, 182, 212, 0.04)',
    border: '1px solid rgba(6, 182, 212, 0.08)',
    borderRadius: '8px',
    marginBottom: '16px',
    fontSize: '12px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  exportAuditBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #0E7490, #06B6D4)',
    border: '1px solid rgba(6, 182, 212, 0.4)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    width: '100%',
    justifyContent: 'center',
  },
  exportAuditBtnDone: {
    background: 'linear-gradient(135deg, #15803D, #22C55E)',
    border: '1px solid rgba(34, 197, 94, 0.4)',
  },
  // ── Non-Human Identity (NHI) Credential ──
  nhiSection: {
    background: 'rgba(139, 92, 246, 0.04)',
    border: '1px solid rgba(139, 92, 246, 0.15)',
    borderRadius: '14px',
    padding: '24px',
  },
  nhiHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '20px',
  },
  nhiTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 700,
    color: '#E2E8F0',
    letterSpacing: '-0.01em',
  },
  nhiBadgeDfars: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  nhiIdCard: {
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: '10px',
    padding: '18px',
    marginBottom: '18px',
    textAlign: 'center' as const,
  },
  nhiIdLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    marginBottom: '8px',
  },
  nhiIdValue: {
    fontSize: '22px',
    fontWeight: 800,
    fontFamily: 'monospace',
    color: '#A78BFA',
    letterSpacing: '0.04em',
    marginBottom: '6px',
  },
  nhiIdSub: {
    fontSize: '11px',
    color: '#64748B',
    letterSpacing: '0.01em',
  },
  nhiMetaGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    marginBottom: '16px',
  },
  nhiMetaItem: {
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(139, 92, 246, 0.08)',
    borderRadius: '8px',
    padding: '12px 14px',
  },
  nhiMetaLabel: {
    fontSize: '10px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: '5px',
  },
  nhiMetaValue: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#CBD5E1',
  },
  nhiFrameworks: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
    marginBottom: '18px',
  },
  nhiFrameworkTag: {
    display: 'inline-flex',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 600,
    fontFamily: 'monospace',
    color: '#A78BFA',
    background: 'rgba(139, 92, 246, 0.08)',
    border: '1px solid rgba(139, 92, 246, 0.15)',
  },
  nhiDownloadBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #6D28D9, #8B5CF6)',
    border: '1px solid rgba(139, 92, 246, 0.4)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    width: '100%',
    justifyContent: 'center',
  },
  nhiDownloadBtnDone: {
    background: 'linear-gradient(135deg, #15803D, #22C55E)',
    border: '1px solid rgba(34, 197, 94, 0.4)',
  },
  nhiHint: {
    margin: '10px 0 0 0',
    fontSize: '11px',
    color: '#64748B',
    lineHeight: 1.5,
    fontStyle: 'italic',
    textAlign: 'center' as const,
  },
  // ── Supervisor Keep-Alive (RAIO Check-In) ──
  raioCheckInCard: {
    marginTop: '18px',
    background: 'rgba(34, 197, 94, 0.04)',
    border: '1px solid rgba(34, 197, 94, 0.15)',
    borderRadius: '10px',
    padding: '18px',
  },
  raioCheckInCardExpired: {
    background: 'rgba(239, 68, 68, 0.04)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
  },
  raioCheckInHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '12px',
  },
  raioCheckInTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#E2E8F0',
    flex: 1,
  },
  raioCheckInBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  raioCheckInBadgeExpired: {
    color: '#EF4444',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.25)',
  },
  raioCheckInBadgePending: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.1)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  raioCheckInMeta: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    marginBottom: '14px',
  },
  raioCheckInMetaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 12px',
    background: 'rgba(15, 23, 42, 0.4)',
    borderRadius: '6px',
  },
  raioCheckInMetaLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  raioCheckInMetaValue: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#CBD5E1',
    fontFamily: 'monospace',
  },
  raioCheckInText: {
    margin: '0 0 14px 0',
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  raioCheckInWarning: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    padding: '10px 14px',
    marginBottom: '14px',
    background: 'rgba(239, 68, 68, 0.06)',
    border: '1px solid rgba(239, 68, 68, 0.15)',
    borderRadius: '8px',
    fontSize: '12px',
    color: '#FCA5A5',
    lineHeight: 1.5,
  },
  raioCheckInBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #15803D, #22C55E)',
    border: '1px solid rgba(34, 197, 94, 0.4)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    width: '100%',
    justifyContent: 'center',
  },
  // ── Council Presentation Mode ──
  resolutionActions: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap' as const,
  },
  presentationToggleBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 700,
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.08)',
    border: '1px solid rgba(245, 158, 11, 0.3)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  // ── Compliance & FOIA Management ──
  complianceFoiaSection: {
    background: 'rgba(244, 114, 182, 0.04)',
    border: '1px solid rgba(244, 114, 182, 0.15)',
    borderRadius: '14px',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '18px',
  },
  complianceFoiaHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  complianceFoiaTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 700,
    color: '#E2E8F0',
    letterSpacing: '-0.01em',
  },
  complianceFoiaBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  foiaRedactionCard: {
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(244, 114, 182, 0.1)',
    borderRadius: '10px',
    padding: '18px',
  },
  foiaRedactionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  foiaRedactionTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#E2E8F0',
  },
  foiaRedactionText: {
    margin: '0 0 14px 0',
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  foiaRedactionCode: {
    padding: '1px 6px',
    borderRadius: '4px',
    fontSize: '12px',
    fontFamily: 'monospace',
    color: '#F472B6',
    background: 'rgba(244, 114, 182, 0.1)',
  },
  sanitizedLogBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#F472B6',
    background: 'rgba(244, 114, 182, 0.1)',
    border: '1px solid rgba(244, 114, 182, 0.25)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  sanitizedLogBtnDone: {
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
  },
  driftCard: {
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(34, 197, 94, 0.1)',
    borderRadius: '10px',
    padding: '18px',
  },
  driftCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
  },
  driftCardTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#E2E8F0',
    flex: 1,
  },
  driftHealthy: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.2)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  sparklineContainer: {
    marginBottom: '14px',
  },
  sparklineAxisRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '4px',
  },
  sparklineAxisLabel: {
    fontSize: '10px',
    color: '#475569',
    fontFamily: 'monospace',
  },
  driftLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: '#94A3B8',
    lineHeight: 1.5,
  },
  pagingCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(244, 114, 182, 0.1)',
    borderRadius: '10px',
    padding: '16px 18px',
  },
  pagingCardLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flex: 1,
  },
  pagingIconWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    background: 'rgba(245, 158, 11, 0.08)',
    border: '1px solid rgba(245, 158, 11, 0.12)',
    flexShrink: 0,
  },
  pagingTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#E2E8F0',
    marginBottom: '3px',
  },
  pagingDesc: {
    fontSize: '12px',
    color: '#64748B',
    lineHeight: 1.4,
  },
  pagingToggle: {
    position: 'relative' as const,
    width: '48px',
    height: '26px',
    borderRadius: '13px',
    background: 'rgba(100, 116, 139, 0.2)',
    border: '1px solid rgba(100, 116, 139, 0.2)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    flexShrink: 0,
    padding: 0,
  },
  pagingToggleOn: {
    background: 'rgba(34, 197, 94, 0.3)',
    border: '1px solid rgba(34, 197, 94, 0.4)',
  },
  pagingToggleKnob: {
    position: 'absolute' as const,
    top: '3px',
    left: '3px',
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    background: '#64748B',
    transition: 'all 0.2s ease',
  },
  pagingToggleKnobOn: {
    left: '25px',
    background: '#22C55E',
  },
  pagingActiveNote: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 14px',
    background: 'rgba(34, 197, 94, 0.06)',
    border: '1px solid rgba(34, 197, 94, 0.1)',
    borderRadius: '8px',
    fontSize: '12px',
    color: '#94A3B8',
    lineHeight: 1.5,
  },
  // ── AI Auditor Bot ──
  auditorCard: {
    background: 'rgba(129, 140, 248, 0.04)',
    border: '1px solid rgba(129, 140, 248, 0.15)',
    borderRadius: '10px',
    padding: '18px',
  },
  auditorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  auditorHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  auditorTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#E2E8F0',
  },
  auditorBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#818CF8',
    background: 'rgba(129, 140, 248, 0.1)',
    border: '1px solid rgba(129, 140, 248, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  auditorToggle: {
    position: 'relative' as const,
    width: '46px',
    height: '24px',
    borderRadius: '12px',
    border: '1px solid rgba(100, 116, 139, 0.3)',
    background: 'rgba(100, 116, 139, 0.2)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    padding: 0,
    flexShrink: 0,
  },
  auditorToggleOn: {
    background: 'rgba(129, 140, 248, 0.3)',
    border: '1px solid rgba(129, 140, 248, 0.5)',
  },
  auditorToggleKnob: {
    position: 'absolute' as const,
    top: '2px',
    left: '2px',
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    background: '#64748B',
    transition: 'all 0.2s ease',
  },
  auditorToggleKnobOn: {
    left: '25px',
    background: '#818CF8',
  },
  auditorDesc: {
    margin: '0 0 16px 0',
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  auditorStatusRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '10px',
    marginBottom: '16px',
  },
  auditorStatusItem: {
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(129, 140, 248, 0.08)',
    borderRadius: '8px',
    padding: '10px 12px',
  },
  auditorStatusLabel: {
    display: 'block',
    fontSize: '10px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    marginBottom: '4px',
  },
  auditorStatusValue: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 700,
    color: '#CBD5E1',
  },
  auditorFindingsHeader: {
    marginBottom: '8px',
  },
  auditorFindingsTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#94A3B8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  auditorFindings: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
    marginBottom: '16px',
  },
  auditorFindingRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    padding: '10px 12px',
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(129, 140, 248, 0.06)',
    borderRadius: '8px',
  },
  auditorSeverity: {
    display: 'inline-flex',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    whiteSpace: 'nowrap' as const,
    marginTop: '2px',
    flexShrink: 0,
  },
  auditorSeverityHigh: {
    color: '#EF4444',
    background: 'rgba(239, 68, 68, 0.12)',
    border: '1px solid rgba(239, 68, 68, 0.25)',
  },
  auditorSeverityMedium: {
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.12)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
  },
  auditorSeverityLow: {
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.12)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
  },
  auditorFindingContent: {
    flex: 1,
    minWidth: 0,
  },
  auditorFindingDesc: {
    fontSize: '12px',
    color: '#CBD5E1',
    lineHeight: 1.5,
    marginBottom: '4px',
  },
  auditorFindingMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap' as const,
  },
  auditorFindingId: {
    fontSize: '10px',
    color: '#818CF8',
    background: 'rgba(129, 140, 248, 0.08)',
    padding: '1px 6px',
    borderRadius: '3px',
    fontFamily: 'monospace',
  },
  auditorFindingTool: {
    fontSize: '10px',
    color: '#64748B',
    fontFamily: 'monospace',
  },
  auditorFindingTime: {
    fontSize: '10px',
    color: '#64748B',
  },
  auditorEmailSection: {
    marginBottom: '16px',
  },
  auditorEmailLabel: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 700,
    color: '#94A3B8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    marginBottom: '8px',
  },
  auditorEmailRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '6px',
  },
  auditorEmailInput: {
    flex: 1,
    padding: '8px 12px',
    fontSize: '13px',
    color: '#E2E8F0',
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(129, 140, 248, 0.2)',
    borderRadius: '6px',
    outline: 'none',
    fontFamily: 'monospace',
  },
  auditorEmailHint: {
    fontSize: '11px',
    color: '#64748B',
    lineHeight: 1.4,
  },
  auditorScanBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#818CF8',
    background: 'rgba(129, 140, 248, 0.1)',
    border: '1px solid rgba(129, 140, 248, 0.25)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    width: '100%',
    justifyContent: 'center',
  },
  auditorScanBtnRunning: {
    color: '#94A3B8',
    background: 'rgba(100, 116, 139, 0.1)',
    border: '1px solid rgba(100, 116, 139, 0.2)',
    cursor: 'wait',
  },
  // ── Baseline Set 1 Upload ──
  baselineSection: {
    background: 'rgba(96, 165, 250, 0.04)',
    border: '1px solid rgba(96, 165, 250, 0.15)',
    borderRadius: '14px',
    padding: '24px',
  },
  baselineHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '14px',
  },
  baselineTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 700,
    color: '#E2E8F0',
    letterSpacing: '-0.01em',
  },
  baselineBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#64748B',
    background: 'rgba(100, 116, 139, 0.1)',
    border: '1px solid rgba(100, 116, 139, 0.2)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  baselineBadgeValid: {
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
  },
  baselineBadgeError: {
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.1)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
  },
  baselineDesc: {
    margin: '0 0 16px 0',
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  baselineUploadZone: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
    background: 'rgba(15, 23, 42, 0.5)',
    border: '2px dashed rgba(96, 165, 250, 0.2)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    marginBottom: '16px',
  },
  baselineFileInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    width: '100%',
  },
  baselineFileName: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#E2E8F0',
  },
  baselineFileSize: {
    fontSize: '12px',
    color: '#64748B',
    marginTop: '2px',
  },
  baselineUploadPrompt: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '8px',
  },
  baselineUploadText: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#94A3B8',
  },
  baselineUploadHint: {
    fontSize: '11px',
    color: '#475569',
    fontFamily: 'monospace',
  },
  baselineErrorBox: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    padding: '14px 16px',
    background: 'rgba(239, 68, 68, 0.06)',
    border: '1px solid rgba(239, 68, 68, 0.15)',
    borderRadius: '8px',
    marginBottom: '16px',
  },
  baselineErrorRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    fontSize: '12px',
    color: '#FCA5A5',
    lineHeight: 1.5,
  },
  baselineExtractedCard: {
    background: 'rgba(34, 197, 94, 0.04)',
    border: '1px solid rgba(34, 197, 94, 0.12)',
    borderRadius: '10px',
    padding: '16px',
    marginBottom: '16px',
  },
  baselineExtractedHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '14px',
  },
  baselineExtractedTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#22C55E',
  },
  baselineExtractedGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
    marginBottom: '12px',
  },
  baselineExtractedItem: {
    background: 'rgba(15, 23, 42, 0.4)',
    borderRadius: '8px',
    padding: '12px',
    textAlign: 'center' as const,
  },
  baselineExtractedLabel: {
    fontSize: '10px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: '6px',
  },
  baselineExtractedValue: {
    fontSize: '16px',
    fontWeight: 800,
    color: '#E2E8F0',
    fontFamily: 'monospace',
  },
  baselineOrdinanceList: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '6px',
  },
  baselineOrdinanceTag: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 600,
    color: '#60A5FA',
    background: 'rgba(96, 165, 250, 0.08)',
    border: '1px solid rgba(96, 165, 250, 0.15)',
    fontFamily: 'monospace',
  },
  baselineHashRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 14px',
    background: 'rgba(96, 165, 250, 0.04)',
    border: '1px solid rgba(96, 165, 250, 0.1)',
    borderRadius: '8px',
    fontSize: '12px',
    color: '#94A3B8',
    flexWrap: 'wrap' as const,
  },
  baselineHashLabel: {
    fontWeight: 700,
    color: '#60A5FA',
    fontSize: '11px',
  },
  baselineHashValue: {
    fontFamily: 'monospace',
    fontSize: '11px',
    color: '#CBD5E1',
    padding: '2px 6px',
    background: 'rgba(15, 23, 42, 0.5)',
    borderRadius: '4px',
    letterSpacing: '0.02em',
  },
  baselineHashLock: {
    marginLeft: 'auto',
    fontSize: '10px',
    fontWeight: 700,
    color: '#22C55E',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  // ── Data Effective Date ──
  effectiveDateRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap' as const,
    padding: '12px 16px',
    background: 'rgba(96, 165, 250, 0.04)',
    border: '1px solid rgba(96, 165, 250, 0.1)',
    borderRadius: '8px',
    marginTop: '10px',
  },
  effectiveDateLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 700,
    color: '#94A3B8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    whiteSpace: 'nowrap' as const,
  },
  effectiveDateInput: {
    padding: '6px 10px',
    fontSize: '13px',
    fontFamily: 'monospace',
    color: '#E2E8F0',
    background: 'rgba(15, 23, 42, 0.6)',
    border: '1px solid rgba(96, 165, 250, 0.2)',
    borderRadius: '6px',
    outline: 'none',
    colorScheme: 'dark' as const,
  },
  effectiveDateHint: {
    fontSize: '11px',
    fontWeight: 600,
    marginLeft: 'auto',
  },
  // ── Data Freshness Warning ──
  freshnessWarningCard: {
    background: 'rgba(245, 158, 11, 0.06)',
    border: '1px solid rgba(245, 158, 11, 0.2)',
    borderRadius: '10px',
    padding: '18px',
  },
  freshnessWarningHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  freshnessWarningTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#F59E0B',
    flex: 1,
  },
  freshnessWarningBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.1)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  freshnessWarningText: {
    margin: '0 0 14px 0',
    fontSize: '13px',
    color: '#D4A054',
    lineHeight: 1.6,
  },
  revalidateBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 18px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.1)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  // ── Freshness Re-Validated ──
  freshnessRevalidatedCard: {
    background: 'rgba(34, 197, 94, 0.06)',
    border: '1px solid rgba(34, 197, 94, 0.2)',
    borderRadius: '10px',
    padding: '18px',
  },
  freshnessRevalidatedHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  freshnessRevalidatedTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#22C55E',
    flex: 1,
  },
  freshnessRevalidatedBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#22C55E',
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  freshnessRevalidatedText: {
    margin: 0,
    fontSize: '13px',
    color: '#86EFAC',
    lineHeight: 1.6,
  },
  // ── Decision Trace Card ──
  decisionTraceCard: {
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(244, 114, 182, 0.12)',
    borderRadius: '10px',
    padding: '18px',
  },
  decisionTraceHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  decisionTraceTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#E2E8F0',
    flex: 1,
  },
  decisionTraceBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#F472B6',
    background: 'rgba(244, 114, 182, 0.1)',
    border: '1px solid rgba(244, 114, 182, 0.2)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  decisionTraceText: {
    margin: '0 0 14px 0',
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  decisionTraceBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 18px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#F472B6',
    background: 'rgba(244, 114, 182, 0.1)',
    border: '1px solid rgba(244, 114, 182, 0.25)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  // ── Policy Recalibration: Version Badge ──
  policyVersionBadge: {
    display: 'inline-flex',
    marginLeft: '8px',
    padding: '2px 8px',
    fontSize: '10px',
    fontWeight: 700,
    color: '#A78BFA',
    background: 'rgba(167, 139, 250, 0.1)',
    border: '1px solid rgba(167, 139, 250, 0.25)',
    borderRadius: '6px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    verticalAlign: 'middle',
  },
  // ── Policy Diff Card ──
  policyDiffCard: {
    marginTop: '12px',
    padding: '16px',
    background: 'rgba(167, 139, 250, 0.04)',
    border: '1px solid rgba(167, 139, 250, 0.15)',
    borderRadius: '10px',
  },
  policyDiffHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '12px',
  },
  policyDiffTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#A78BFA',
  },
  policyDiffBadge: {
    marginLeft: 'auto',
    padding: '2px 8px',
    fontSize: '9px',
    fontWeight: 800,
    color: '#A78BFA',
    background: 'rgba(167, 139, 250, 0.12)',
    border: '1px solid rgba(167, 139, 250, 0.25)',
    borderRadius: '4px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  },
  policyDiffTable: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0px',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid rgba(167, 139, 250, 0.1)',
  },
  policyDiffTableHeader: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 1fr 1fr 40px',
    padding: '8px 12px',
    background: 'rgba(167, 139, 250, 0.08)',
    fontSize: '10px',
    fontWeight: 700,
    color: '#A78BFA',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  policyDiffColField: {},
  policyDiffColOld: { textAlign: 'right' as const },
  policyDiffColNew: { textAlign: 'right' as const },
  policyDiffColDir: { textAlign: 'center' as const },
  policyDiffRow: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 1fr 1fr 40px',
    padding: '8px 12px',
    fontSize: '12px',
    borderTop: '1px solid rgba(167, 139, 250, 0.06)',
    background: 'rgba(15, 23, 42, 0.3)',
  },
  policyDiffCellField: {
    fontWeight: 600,
    color: '#CBD5E1',
  },
  policyDiffCellOld: {
    textAlign: 'right' as const,
    color: '#94A3B8',
    textDecoration: 'line-through',
    opacity: 0.7,
  },
  policyDiffCellNew: {
    textAlign: 'right' as const,
    color: '#F1F5F9',
    fontWeight: 600,
  },
  policyDiffCellDir: {
    textAlign: 'center' as const,
    fontWeight: 700,
    fontSize: '13px',
  },
  policyDiffHashCompare: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: '10px',
    padding: '8px 12px',
    background: 'rgba(15, 23, 42, 0.4)',
    borderRadius: '6px',
    fontSize: '11px',
    flexWrap: 'wrap' as const,
  },
  policyDiffHashLabel: {
    color: '#A78BFA',
    fontWeight: 700,
    fontSize: '10px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  policyDiffHashCode: {
    fontFamily: 'monospace',
    fontSize: '11px',
    color: '#CBD5E1',
    padding: '2px 6px',
    background: 'rgba(15, 23, 42, 0.6)',
    borderRadius: '4px',
  },
  policyDiffHashArrow: {
    color: '#A78BFA',
    fontWeight: 700,
    fontSize: '14px',
  },
  // ── Compliance Alert Banners ──
  complianceAlertCritical: {
    marginBottom: '16px',
    padding: '18px',
    background: 'rgba(239, 68, 68, 0.06)',
    border: '2px solid rgba(239, 68, 68, 0.4)',
    borderRadius: '12px',
    animation: 'pulse 2s ease-in-out infinite',
  },
  complianceAlertWarning: {
    marginBottom: '16px',
    padding: '18px',
    background: 'rgba(245, 158, 11, 0.06)',
    border: '2px solid rgba(245, 158, 11, 0.35)',
    borderRadius: '12px',
  },
  complianceAlertIconRow: {
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
  },
  complianceAlertIconCritical: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '44px',
    height: '44px',
    borderRadius: '12px',
    background: 'linear-gradient(135deg, #DC2626, #EF4444)',
    flexShrink: 0,
  },
  complianceAlertIconWarning: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '44px',
    height: '44px',
    borderRadius: '12px',
    background: 'linear-gradient(135deg, #B45309, #F59E0B)',
    flexShrink: 0,
  },
  complianceAlertContent: {
    flex: 1,
    minWidth: 0,
  },
  complianceAlertTitleCritical: {
    fontSize: '15px',
    fontWeight: 800,
    color: '#EF4444',
    letterSpacing: '0.01em',
    marginBottom: '6px',
  },
  complianceAlertTitleWarning: {
    fontSize: '15px',
    fontWeight: 800,
    color: '#F59E0B',
    letterSpacing: '0.01em',
    marginBottom: '6px',
  },
  complianceAlertDesc: {
    fontSize: '12px',
    color: '#CBD5E1',
    lineHeight: 1.6,
    margin: '0 0 10px 0',
  },
  complianceAlertCode: {
    display: 'block',
    padding: '8px 12px',
    marginBottom: '12px',
    fontSize: '11px',
    fontFamily: 'monospace',
    color: '#FCA5A5',
    background: 'rgba(239, 68, 68, 0.08)',
    border: '1px solid rgba(239, 68, 68, 0.15)',
    borderRadius: '6px',
    wordBreak: 'break-all' as const,
  },
  complianceAlertActions: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap' as const,
  },
  complianceAlertBtnCritical: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 18px',
    fontSize: '12px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #DC2626, #EF4444)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    letterSpacing: '0.01em',
  },
  complianceAlertBtnRetry: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 18px',
    fontSize: '12px',
    fontWeight: 700,
    color: '#94A3B8',
    background: 'transparent',
    border: '1px solid rgba(100, 116, 139, 0.25)',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  complianceAlertBtnWarning: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 18px',
    fontSize: '12px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #B45309, #D97706)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  complianceAlertBtnContact: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 18px',
    fontSize: '12px',
    fontWeight: 700,
    color: '#94A3B8',
    background: 'transparent',
    border: '1px solid rgba(100, 116, 139, 0.25)',
    borderRadius: '8px',
    cursor: 'pointer',
  },
};

// ===========================================
// RESOLUTION MODAL STYLES
// ===========================================
export const resolutionStyles: { [key: string]: React.CSSProperties } = {
  modalContent: {
    background: '#0F172A',
    border: '1px solid rgba(245, 158, 11, 0.2)',
    borderRadius: '16px',
    width: '95%',
    maxWidth: '800px',
    maxHeight: '90vh',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  resNumBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.12)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
  },
  modalBody: {
    padding: '24px',
    overflowY: 'auto',
    flex: 1,
  },
  docMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '16px',
    flexWrap: 'wrap',
  },
  docMetaItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#94A3B8',
  },
  textArea: {
    width: '100%',
    minHeight: '500px',
    padding: '24px',
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(245, 158, 11, 0.15)',
    borderRadius: '10px',
    color: '#CBD5E1',
    fontSize: '13px',
    fontFamily: '"Georgia", "Times New Roman", serif',
    lineHeight: 1.8,
    resize: 'vertical' as const,
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  disclaimer: {
    marginTop: '12px',
    fontSize: '11px',
    color: '#64748B',
    lineHeight: 1.5,
    fontStyle: 'italic',
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 24px',
    borderTop: '1px solid rgba(245, 158, 11, 0.1)',
    background: 'rgba(15, 23, 42, 0.5)',
  },
  closeBtn: {
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#94A3B8',
    background: 'transparent',
    border: '1px solid rgba(100, 116, 139, 0.2)',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  downloadBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #B45309, #F59E0B)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
  },
};

// ===========================================
// COUNCIL PRESENTATION MODE STYLES
// ===========================================
export const presentationStyles: { [key: string]: React.CSSProperties } = {
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 9999,
    background: 'rgba(0, 0, 0, 0.92)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    background: '#030712',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 32px',
    borderBottom: '1px solid rgba(245, 158, 11, 0.12)',
    background: 'rgba(15, 23, 42, 0.6)',
    flexShrink: 0,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  headerTitle: {
    fontSize: '20px',
    fontWeight: 800,
    color: '#F1F5F9',
    letterSpacing: '-0.02em',
  },
  headerBadge: {
    display: 'inline-flex',
    padding: '4px 12px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.12)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  headerAgency: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#94A3B8',
  },
  closeBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    background: 'rgba(100, 116, 139, 0.1)',
    border: '1px solid rgba(100, 116, 139, 0.2)',
    color: '#94A3B8',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  metricsArea: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 32px',
    gap: '36px',
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '28px',
    width: '100%',
    maxWidth: '1200px',
  },
  metricCard: {
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(100, 116, 139, 0.1)',
    borderRadius: '20px',
    padding: '40px 32px',
    textAlign: 'center' as const,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
  },
  metricIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '64px',
    height: '64px',
    borderRadius: '16px',
    background: 'rgba(255, 255, 255, 0.03)',
    marginBottom: '8px',
  },
  metricLabel: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#94A3B8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  },
  metricValue: {
    fontSize: '48px',
    fontWeight: 900,
    letterSpacing: '-0.03em',
    lineHeight: 1.1,
  },
  metricSub: {
    fontSize: '13px',
    color: '#64748B',
    lineHeight: 1.5,
    maxWidth: '280px',
  },
  contextBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    padding: '14px 24px',
    background: 'rgba(15, 23, 42, 0.4)',
    border: '1px solid rgba(100, 116, 139, 0.08)',
    borderRadius: '12px',
    flexWrap: 'wrap' as const,
  },
  contextItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#94A3B8',
  },
  contextDivider: {
    width: '1px',
    height: '16px',
    background: 'rgba(100, 116, 139, 0.2)',
  },
  footer: {
    padding: '16px 32px',
    borderTop: '1px solid rgba(100, 116, 139, 0.08)',
    background: 'rgba(15, 23, 42, 0.4)',
    flexShrink: 0,
  },
  disclaimer: {
    margin: 0,
    fontSize: '11px',
    color: '#475569',
    lineHeight: 1.6,
    textAlign: 'center' as const,
    fontStyle: 'italic',
  },
};

// ===========================================
// DECISION TRACE MODAL STYLES
// ===========================================
export const traceStyles: { [key: string]: React.CSSProperties } = {
  modalContent: {
    background: '#0F172A',
    border: '1px solid rgba(244, 114, 182, 0.2)',
    borderRadius: '16px',
    width: '95%',
    maxWidth: '680px',
    maxHeight: '90vh',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  dutyBadge: {
    display: 'inline-flex',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: '#F472B6',
    background: 'rgba(244, 114, 182, 0.12)',
    border: '1px solid rgba(244, 114, 182, 0.25)',
  },
  body: {
    padding: '24px',
    overflowY: 'auto',
    flex: 1,
  },
  sampleHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '24px',
    flexWrap: 'wrap',
  },
  sampleLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#94A3B8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  },
  sampleId: {
    fontFamily: 'monospace',
    fontSize: '12px',
    fontWeight: 700,
    color: '#F472B6',
    padding: '2px 8px',
    background: 'rgba(244, 114, 182, 0.08)',
    borderRadius: '4px',
  },
  sampleTime: {
    fontSize: '12px',
    color: '#64748B',
    marginLeft: 'auto',
  },
  flow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0px',
    marginBottom: '24px',
  },
  step: {
    display: 'flex',
    gap: '16px',
  },
  stepNode: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flexShrink: 0,
    width: '40px',
  },
  stepIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    flexShrink: 0,
  },
  stepConnector: {
    width: '2px',
    flex: 1,
    minHeight: '16px',
    background: 'rgba(100, 116, 139, 0.15)',
    marginTop: '4px',
  },
  stepContent: {
    flex: 1,
    paddingBottom: '4px',
  },
  stepLabel: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#E2E8F0',
    marginBottom: '6px',
  },
  stepDetail: {
    fontSize: '13px',
    color: '#94A3B8',
    lineHeight: 1.6,
    marginBottom: '8px',
  },
  stepMeta: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '6px',
  },
  stepMetaTag: {
    display: 'inline-flex',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: 600,
    fontFamily: 'monospace',
    color: '#64748B',
    background: 'rgba(100, 116, 139, 0.08)',
    border: '1px solid rgba(100, 116, 139, 0.12)',
  },
  arrowRow: {
    display: 'flex',
    justifyContent: 'center',
    width: '40px',
    padding: '2px 0',
  },
  auditFooter: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    padding: '14px 16px',
    background: 'rgba(34, 197, 94, 0.04)',
    border: '1px solid rgba(34, 197, 94, 0.1)',
    borderRadius: '8px',
    fontSize: '12px',
    color: '#94A3B8',
    lineHeight: 1.6,
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    padding: '16px 24px',
    borderTop: '1px solid rgba(244, 114, 182, 0.1)',
    background: 'rgba(15, 23, 42, 0.5)',
  },
  closeBtn: {
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#94A3B8',
    background: 'transparent',
    border: '1px solid rgba(100, 116, 139, 0.2)',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  // ── Citizen Appeal — M-26-04 Transparency ──
  appealSection: {
    marginTop: '20px',
    padding: '16px',
    background: 'rgba(245, 158, 11, 0.04)',
    border: '1px solid rgba(245, 158, 11, 0.15)',
    borderRadius: '10px',
  },
  appealNote: {
    display: 'flex',
    gap: '10px',
    fontSize: '12px',
    color: '#CBD5E1',
    lineHeight: 1.6,
    marginBottom: '14px',
  },
  appealBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '12px 20px',
    fontSize: '13px',
    fontWeight: 700,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #B45309, #D97706)',
    border: '1px solid rgba(245, 158, 11, 0.4)',
    borderRadius: '8px',
    cursor: 'pointer',
    letterSpacing: '0.01em',
  },
  appealReceiptCard: {
    padding: '14px',
    background: 'rgba(34, 197, 94, 0.04)',
    border: '1px solid rgba(34, 197, 94, 0.2)',
    borderRadius: '8px',
  },
  appealReceiptHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '12px',
  },
  appealReceiptTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#22C55E',
  },
  appealReceiptBadge: {
    marginLeft: 'auto',
    padding: '2px 8px',
    fontSize: '9px',
    fontWeight: 800,
    color: '#F59E0B',
    background: 'rgba(245, 158, 11, 0.1)',
    border: '1px solid rgba(245, 158, 11, 0.25)',
    borderRadius: '4px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  appealReceiptGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  appealReceiptRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '6px 10px',
    background: 'rgba(15, 23, 42, 0.3)',
    borderRadius: '6px',
  },
  appealReceiptLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#94A3B8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  appealReceiptValue: {
    fontFamily: 'monospace',
    fontSize: '11px',
    color: '#CBD5E1',
    padding: '2px 6px',
    background: 'rgba(15, 23, 42, 0.5)',
    borderRadius: '4px',
  },
  appealReceiptFooter: {
    marginTop: '10px',
    fontSize: '11px',
    color: '#64748B',
    fontStyle: 'italic',
    textAlign: 'center' as const,
  },
};
